import type { EcologyEvent, EcologyResonance, EcologyResonanceResult, EvolutionLog, EvolutionNode, GameState, LeaderboardScoreBreakdown, PlanetProfile, Resources, SpeciesRecord, Talent } from "@eco-era/shared";
export declare const OFFLINE_ACCUMULATION_HOURS = 5;
export declare const evolutionNodes: EvolutionNode[];
export declare const ecologyEvents: EcologyEvent[];
export declare const ecologyResonances: EcologyResonance[];
export declare const talentCatalog: Talent[];
export declare function createInitialState(id: string, name?: string, initialTalentId?: string): GameState;
export declare function calculateResourceDelta(state: GameState, elapsedSeconds: number): Resources;
export declare function unclaimedResourceCapacity(state: GameState): Resources;
export declare function advanceState(input: GameState, now?: Date): GameState;
export declare function applyEnvironmentAction(input: GameState, action: string): GameState;
export declare function unlockEvolutionNode(input: GameState, nodeId: string): GameState;
export declare function availableEcologyEvents(state: GameState): EcologyEvent[];
export declare function rollEcologyEvent(state: GameState): EcologyEvent | null;
export declare function ecologyEventChanceFor(state: GameState): number;
export declare function applyEcologyEventChoice(input: GameState, eventId: string, optionId: string): GameState;
export declare function availableEcologyResonances(state: GameState, now?: Date): EcologyResonance[];
export declare function applyEcologyResonance(input: GameState, resonanceId: string, now?: Date): {
    state: GameState;
    resonanceResult: EcologyResonanceResult;
};
export declare function selectTalent(input: GameState, talentId: string): GameState;
export declare function applyInstantEffect(state: GameState, talent: Talent): GameState;
export declare function rollTalentChoices(state?: GameState, count?: number): Talent[];
export declare function normalizeGameState(state: GameState): GameState;
export type ThirdChapterDebugStage = "exposed" | "shore" | "event" | "exchange";
export declare function buildThirdChapterDebugSave(id: string, stage?: ThirdChapterDebugStage): GameState;
export declare function evaluateHiddenTraces(input: GameState, now?: Date): GameState;
export declare function canUnlockEvolutionNode(state: GameState, nodeId: string): boolean;
export declare function calculatePlanetProfile(state: GameState): PlanetProfile;
export declare function calculateEcologyScore(input: GameState): number;
export declare function calculateEcologyScoreBreakdown(input: GameState): LeaderboardScoreBreakdown;
export declare function productionMultiplierFor(state: GameState): Resources;
export declare function previewEvolutionNodeProduction(input: GameState, nodeId: string): {
    before: Resources;
    after: Resources;
    ratio: number;
    copy: string;
};
export declare function generateSpeciesTemplate(state: GameState): SpeciesRecord;
export declare function createLog(type: EvolutionLog["type"], message: string): EvolutionLog;
//# sourceMappingURL=index.d.ts.map