import * as Phaser from "phaser";
type ElementType = "crystal" | "spark" | "droplet" | "pulse";
type Outcome = "positive" | "negative" | "rare";
export declare class HomeScene extends Phaser.Scene {
    private poolInner;
    private poolOuter;
    private poolShape;
    private poolImage;
    private particleEmitters;
    private organisms;
    private lightBeams;
    private resourceOrbs;
    private titleText;
    private poolPulseTime;
    private organismSpawnTimer;
    private tapRipples;
    private causticGraphics;
    private algaeGraphics;
    private cloudGraphics;
    private ecologyStageGraphics;
    private causticDrift;
    private poolVertices;
    private ambientRedrawTimer;
    private ecologyStageRedrawTimer;
    private dragElements;
    private draggedElement;
    private dragTrail;
    private poolHintText;
    private poolHintArrow;
    private absorbCount;
    private elementSpawnTimer;
    private nextSpawnDelay;
    static readonly MAX_ELEMENTS = 2;
    static readonly POOL_ABSORB_RADIUS = 112;
    static readonly ELEMENT_POOL_AVOID_RADIUS = 150;
    onAbsorb?: (type: ElementType, outcome: Outcome) => void;
    constructor();
    preload(): void;
    create(): void;
    update(_time: number, delta: number): void;
    private updateSpawning;
    private spawnElement;
    private spawnElementOfType;
    private playElementEnter;
    private trimExtraElements;
    private releaseElement;
    private removeDragElement;
    private updateDragElements;
    private randomElementPosition;
    private keepElementInPlayArea;
    private getTapElement;
    private onPointerDown;
    private onPointerMove;
    private onPointerUp;
    private updateDragTrail;
    private absorbElement;
    private playAbsorbFeedback;
    spawnOrganism(): void;
    private updateOrganisms;
    private updateResourceOrbs;
    private updateCaustics;
    private updateAlgaeAndClouds;
    private updateLightBeams;
    private drawCrystalElement;
    private drawSparkElement;
    private drawDropletElement;
    private drawPulseElement;
    private drawPulseFrame;
    private createBackground;
    private createLightBeams;
    private createPool;
    private createAlgaeAndClouds;
    private createEcologyStageLayer;
    private updateEcologyStageLayer;
    private createFloatingParticles;
    private createResourceOrbs;
    private createTitle;
    private createPoolHint;
    private createProceduralTextures;
}
export {};
//# sourceMappingURL=HomeScene.d.ts.map